<?php
// Simple PDF generation using TCPDF alternative - FPDF
// This avoids the Dompdf issues entirely

// Database and session setup
$root_path = dirname(__DIR__, 2);
require_once $root_path . '/config/session/employee_session.php';
require_once $root_path . '/config/db.php';

// Authentication check
if (!is_employee_logged_in()) {
    header('Location: ' . $root_path . '/pages/management/auth/login.php');
    exit();
}

// Role-based access control  
$allowed_roles = ['admin', 'dho', 'cashier', 'records_officer'];
if (!in_array($_SESSION['role'], $allowed_roles)) {
    header('Location: ' . $root_path . '/pages/management/dashboard.php');
    exit();
}

// Check if FPDF is available, if not, create a simple text-based PDF
if (!file_exists($root_path . '/vendor/setasign/fpdf/fpdf.php')) {
    // Create a simple text-based report that can be saved as PDF
    header('Content-Type: text/plain; charset=UTF-8');
    header('Content-Disposition: attachment; filename="Referral_Summary_Report_' . date('Y-m-d_H-i-s') . '.txt"');
    
    // Get filter parameters
    $filter_type = $_GET['filter_type'] ?? $_POST['filter_type'] ?? 'month_range';
    $date_from = $_GET['date_from'] ?? $_POST['date_from'] ?? date('Y-m-01');
    $date_to = $_GET['date_to'] ?? $_POST['date_to'] ?? date('Y-m-t');
    
    try {
        // Key metrics query
        $metrics_query = "
            SELECT 
                COUNT(*) as total_referrals,
                SUM(CASE WHEN status = 'accepted' THEN 1 ELSE 0 END) as accepted_referrals,
                SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled_referrals,
                SUM(CASE WHEN destination_type = 'external' THEN 1 ELSE 0 END) as external_issued,
                SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as active_referrals
            FROM referrals 
            WHERE DATE(referral_date) BETWEEN ? AND ?
        ";
        
        $stmt = $pdo->prepare($metrics_query);
        $stmt->execute([$date_from, $date_to]);
        $metrics = $stmt->fetch(PDO::FETCH_ASSOC);
        
        $completion_rate = $metrics['total_referrals'] > 0 
            ? round(($metrics['accepted_referrals'] / $metrics['total_referrals']) * 100, 1) 
            : 0;
            
        // Generate text report
        echo "================================================================================\n";
        echo "                        REFERRAL SUMMARY REPORT\n";
        echo "                      Republic of the Philippines\n";
        echo "                        City Health Office\n";
        echo "                         Koronadal City\n";
        echo "================================================================================\n\n";
        echo "Report Period: " . date('F j, Y', strtotime($date_from)) . " - " . date('F j, Y', strtotime($date_to)) . "\n";
        echo "Generated: " . date('F j, Y \a\t g:i A') . "\n";
        echo "Generated by: " . ($_SESSION['first_name'] ?? 'Unknown') . ' ' . ($_SESSION['last_name'] ?? 'User') . " (" . ($_SESSION['role'] ?? 'Unknown') . ")\n\n";
        
        echo "KEY METRICS SUMMARY:\n";
        echo "================================================================================\n";
        echo "Total Referrals:      " . number_format($metrics['total_referrals']) . "\n";
        echo "Accepted Referrals:   " . number_format($metrics['accepted_referrals']) . "\n";
        echo "Cancelled Referrals:  " . number_format($metrics['cancelled_referrals']) . "\n";
        echo "External Issued:      " . number_format($metrics['external_issued']) . "\n";
        echo "Active Referrals:     " . number_format($metrics['active_referrals']) . "\n";
        echo "Completion Rate:      " . $completion_rate . "%\n\n";
        
        // Get top facility transfers
        $facility_query = "
            SELECT 
                rf.name as referring_facility,
                COALESCE(tf.name, r.external_facility_name, 'External Facility') as referred_to_facility,
                COUNT(*) as total_referrals,
                SUM(CASE WHEN r.status = 'accepted' THEN 1 ELSE 0 END) as accepted,
                SUM(CASE WHEN r.status = 'cancelled' THEN 1 ELSE 0 END) as cancelled
            FROM referrals r
            LEFT JOIN facilities rf ON r.referring_facility_id = rf.facility_id
            LEFT JOIN facilities tf ON r.referred_to_facility_id = tf.facility_id
            WHERE DATE(r.referral_date) BETWEEN ? AND ?
            GROUP BY r.referring_facility_id, r.referred_to_facility_id, r.external_facility_name
            ORDER BY total_referrals DESC
            LIMIT 10
        ";
        
        $facility_stmt = $pdo->prepare($facility_query);
        $facility_stmt->execute([$date_from, $date_to]);
        $facility_transfers = $facility_stmt->fetchAll(PDO::FETCH_ASSOC);
        
        if (!empty($facility_transfers)) {
            echo "FACILITY-TO-FACILITY TRANSFERS (TOP 10):\n";
            echo "================================================================================\n";
            echo sprintf("%-25s %-25s %8s %8s %8s\n", "Referring Facility", "Referred To Facility", "Total", "Accepted", "Cancelled");
            echo "--------------------------------------------------------------------------------\n";
            
            foreach ($facility_transfers as $transfer) {
                echo sprintf("%-25s %-25s %8s %8s %8s\n", 
                    substr($transfer['referring_facility'] ?: 'Unknown', 0, 24),
                    substr($transfer['referred_to_facility'], 0, 24),
                    number_format($transfer['total_referrals']),
                    number_format($transfer['accepted']),
                    number_format($transfer['cancelled'])
                );
            }
            echo "\n";
        }
        
        echo "REPORT SUMMARY:\n";
        echo "================================================================================\n";
        echo "This report contains referral data for the selected period.\n";
        echo "Generated on " . date('F j, Y \a\t g:i A') . " by the City Health Office, Koronadal City.\n";
        echo "For questions about this report, please contact the City Health Office.\n\n";
        echo "================================================================================\n";
        echo "                          END OF REPORT\n";
        echo "================================================================================\n";
        
    } catch (Exception $e) {
        echo "Error generating report: " . $e->getMessage();
    }
    
    exit();
}

// If we get here, we could implement FPDF, but for now redirect to HTML version
header('Location: export_referral_summary_html.php?' . http_build_query($_GET ?: $_POST));
exit();
?>