<?php
// Simple test to check if Dompdf is working
$root_path = dirname(dirname(__DIR__));
require_once $root_path . '/vendor/autoload.php';

// Test basic Dompdf functionality
use Dompdf\Dompdf;
use Dompdf\Options;

try {
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isPhpEnabled', true);

    $dompdf = new Dompdf($options);
    
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test PDF</title>
        <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #0077b6; }
        </style>
    </head>
    <body>
        <h1>PDF Export Test</h1>
        <p>This is a test PDF generated by Dompdf.</p>
        <p>Generated: ' . date('F j, Y \a\t g:i A') . '</p>
        <table border="1" style="width: 100%; border-collapse: collapse;">
            <tr>
                <th>Column 1</th>
                <th>Column 2</th>
                <th>Column 3</th>
            </tr>
            <tr>
                <td>Data 1</td>
                <td>Data 2</td>
                <td>Data 3</td>
            </tr>
        </table>
    </body>
    </html>';
    
    $dompdf->loadHtml($html);
    $dompdf->setPaper('letter', 'portrait');
    $dompdf->render();
    
    $filename = 'test_pdf_' . date('Ymd_His') . '.pdf';
    
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: private, max-age=0, must-revalidate');
    header('Pragma: public');
    
    echo $dompdf->output();
    
} catch (Exception $e) {
    echo '<h1>PDF Test Failed</h1>';
    echo '<p>Error: ' . htmlspecialchars($e->getMessage()) . '</p>';
    echo '<p>File: ' . htmlspecialchars($e->getFile()) . '</p>';
    echo '<p>Line: ' . $e->getLine() . '</p>';
}
?>